version: 2

jobs:
  build:
    docker:
      - image: node:12
    steps:
      - checkout
      - run: echo "build"
  test:
    docker:
      - image: node:12
    steps:
      - checkout
      - run: echo "test"
  deploy_staging:
    docker:
      - image: node:12
    steps:
      - checkout
      - run: echo "prepare-staging-deployment.sh"
      - deploy:
          name: Staging
          command: |
            echo "Staging deployment..."
            echo "Then Hook GFP: staging"
            GFP_DEPLOYMENT_ENVIRONMENT=staging; wget -qO- --post-data="{\"branch\":\"${CIRCLE_BRANCH}\", \"environment\":\"${GFP_DEPLOYMENT_ENVIRONMENT}\" }" --header='Content-Type:application/json' 'https://slavagitproflow.localtunnel.me/deployment/webhook/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InNsYXZhaGF0bnVrZSIsInJlcG8iOiJzbGF2YWhhdG51a2UvZ2ZwMiIsInNlcnZpY2UiOiJnaXRodWIiLCJpYXQiOjE1NjU2MTQ3OTUsImV4cCI6MjE5Njc2Njc5NX0.q4oucbcCiBgu2cwXj3B5OxzI0770WXX1Q6eeOHzJrD4';
  deploy_production:
    docker:
      - image: node:12
    steps:
      - checkout
      - run: echo "prepare-production-deployment.sh"
      - deploy:
          name: Production
          command: |
            echo "Production deployment..."
            echo "Then Hook GFP: production"
            GFP_DEPLOYMENT_ENVIRONMENT=production; wget -qO- --post-data="{\"branch\":\"${CIRCLE_BRANCH}\", \"environment\":\"${GFP_DEPLOYMENT_ENVIRONMENT}\" }" --header='Content-Type:application/json' 'https://slavagitproflow.localtunnel.me/deployment/webhook/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InNsYXZhaGF0bnVrZSIsInJlcG8iOiJzbGF2YWhhdG51a2UvZ2ZwMiIsInNlcnZpY2UiOiJnaXRodWIiLCJpYXQiOjE1NjU2MTQ3OTUsImV4cCI6MjE5Njc2Njc5NX0.q4oucbcCiBgu2cwXj3B5OxzI0770WXX1Q6eeOHzJrD4';

workflows:
  version: 2
  build_test_deploy:
    jobs:
      - build
      - test
      - deploy_staging:
          - filters:
              branches:
                only:
                  - master
      - deploy_production:
          - filters:
              branches:
                only:
                  - prod

#
#jobs:
#  build:
#    docker:
#      - image: node:12
#    steps:
#      - checkout
#      - run: echo "run-tests.sh"
#      - deploy:
#          name: Staging
#          command: |
#            GFP_DEPLOYMENT_ENVIRONMENT=staging; wget -qO- --post-data="{\"branch\":\"${CIRCLE_BRANCH}\", \"environment\":\"${GFP_DEPLOYMENT_ENVIRONMENT}\" }" --header='Content-Type:application/json' 'https://slavagitproflow.localtunnel.me/deployment/webhook/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InNsYXZhaGF0bnVrZSIsInJlcG8iOiJzbGF2YWhhdG51a2UvZ2ZwMiIsInNlcnZpY2UiOiJnaXRodWIiLCJpYXQiOjE1NjU2MTQ3OTUsImV4cCI6MjE5Njc2Njc5NX0.q4oucbcCiBgu2cwXj3B5OxzI0770WXX1Q6eeOHzJrD4';
#
#      - deploy:
#          name: Production
#          command: |
#            GFP_DEPLOYMENT_ENVIRONMENT=production; wget -qO- --post-data="{\"branch\":\"${CIRCLE_BRANCH}\", \"environment\":\"${GFP_DEPLOYMENT_ENVIRONMENT}\" }" --header='Content-Type:application/json' 'https://slavagitproflow.localtunnel.me/deployment/webhook/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InNsYXZhaGF0bnVrZSIsInJlcG8iOiJzbGF2YWhhdG51a2UvZ2ZwMiIsInNlcnZpY2UiOiJnaXRodWIiLCJpYXQiOjE1NjU2MTQ3OTUsImV4cCI6MjE5Njc2Njc5NX0.q4oucbcCiBgu2cwXj3B5OxzI0770WXX1Q6eeOHzJrD4';
