workflows:
  version: 2
  build_test_deploy:
    jobs:
      - build
      - test:
          requires:
            - build
      - deploy_staging:
          requires:
            - test
          filters:
            branches:
              only:
                - master
      - deploy_production:
          requires:
            - test
          filters:
            branches:
              only:
                - prod
jobs:
  build:
    docker:
      - image: node:12
    steps:
      - checkout
      - run: echo "build dependencies and project assets"
  test:
    docker:
      - image: node:12
    steps:
      - checkout
      - run: echo "test"
  deploy_staging:
    docker:
      - image: node:12
    steps:
      - checkout
      - run: echo "prepare-staging-deployment.sh"
      - deploy:
          name: Staging
          command: |
            echo "Staging deployment..."
            echo "Then Hook GFP: staging"
            GFP_DEPLOYMENT_ENVIRONMENT=staging; wget -qO- --post-data="{\"branch\":\"${CIRCLE_BRANCH}\", \"environment\":\"${GFP_DEPLOYMENT_ENVIRONMENT}\" }" --header='Content-Type:application/json' 'https://slavagitproflow.serveo.net/deployment/webhook/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InNsYXZhaGF0bnVrZSIsInJlcG8iOiJzbGF2YWhhdG51a2UvZ2ZwMiIsInNlcnZpY2UiOiJnaXRodWIiLCJpYXQiOjE1NjU5Nzg4NTIsImV4cCI6MjE5NzEzMDg1Mn0.gUAV0g1IfxuCSN68YdUu3D4iSV_gJSQ3zD7KspH9EFc--' --content-on-error=on;
  deploy_production:
    docker:
      - image: node:12
    steps:
      - checkout
      - run: echo "prepare-production-deployment.sh"
      - deploy:
          name: Production
          command: |
            echo "Production deployment..."
            echo "Then Hook GFP: production"
            GFP_DEPLOYMENT_ENVIRONMENT=production; wget -qO- --post-data="{\"branch\":\"${CIRCLE_BRANCH}\", \"environment\":\"${GFP_DEPLOYMENT_ENVIRONMENT}\" }" --header='Content-Type:application/json' 'https://slavagitproflow.serveo.net/deployment/webhook/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InNsYXZhaGF0bnVrZSIsInJlcG8iOiJzbGF2YWhhdG51a2UvZ2ZwMiIsInNlcnZpY2UiOiJnaXRodWIiLCJpYXQiOjE1NjU5Nzg4NTIsImV4cCI6MjE5NzEzMDg1Mn0.gUAV0g1IfxuCSN68YdUu3D4iSV_gJSQ3zD7KspH9EFc--' --content-on-error=on;